// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ffmpeg.djinni

#pragma once

namespace dc { namespace platform {

class TranscodeListener {
public:
    virtual ~TranscodeListener() {}

    virtual void OnProcess(float percent) = 0;
};


} }  // namespace dc::platform




