// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ffmpeg.djinni

package com.dongci.sun.gpuimglibrary.libffmpeg;

/** Copyright (c) 2016 Zepp Labs, Inc. All rights reserved. */
public enum FfmpegLogLevel {
    LOG_VERBOSE,
    LOG_DEBUG,
    LOG_INFO,
    LOG_WARN,
    LOG_ERROR,
    LOG_FATAL,
    LOG_NONE,
    ;
}
