// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

package com.dc.platform.voicebeating;

import android.os.Parcel;
import android.os.Parcelable;

import java.util.ArrayList;
/*
yangjiangang
 */
public final class VoiceAnalysisInfo implements Parcelable {


    /*package*/ int startTimeMs;

    /*package*/ int endTimeMs;

    /*package*/ ArrayList<VoicePitchInfo> pitchSeq;

    /*package*/ ArrayList<VoiceNoteInfo> noteSeq;

    /*package*/ boolean bValid;

    /*package*/ int assetId;

    /*package*/ String voiceName;

    public VoiceAnalysisInfo(){

    }

    public VoiceAnalysisInfo(
            int startTimeMs,
            int endTimeMs,
            ArrayList<VoicePitchInfo> pitchSeq,
            ArrayList<VoiceNoteInfo> noteSeq,
            boolean bValid,
            int assetId,
            String voiceName) {
        this.startTimeMs = startTimeMs;
        this.endTimeMs = endTimeMs;
        this.pitchSeq = pitchSeq;
        this.noteSeq = noteSeq;
        this.bValid = bValid;
        this.assetId = assetId;
        this.voiceName = voiceName;
    }

    public int getStartTimeMs() {
        return startTimeMs;
    }

    public int getEndTimeMs() {
        return endTimeMs;
    }

    public ArrayList<VoicePitchInfo> getPitchSeq() {
        return pitchSeq;
    }

    public ArrayList<VoiceNoteInfo> getNoteSeq() {
        return noteSeq;
    }

    public boolean getBValid() {
        return bValid;
    }

    public int getAssetId() {
        return assetId;
    }

    public String getVoiceName() {
        return voiceName;
    }

    @Override
    public String toString() {
        return "VoiceAnalysisInfo{" +
                "startTimeMs=" + startTimeMs +
                "," + "endTimeMs=" + endTimeMs +
                "," + "pitchSeq=" + pitchSeq +
                "," + "noteSeq=" + noteSeq +
                "," + "bValid=" + bValid +
                "," + "assetId=" + assetId +
                "," + "voiceName=" + voiceName +
        "}";
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeInt(this.startTimeMs);
        dest.writeInt(this.endTimeMs);
        dest.writeList(this.pitchSeq);
        dest.writeList(this.noteSeq);
        dest.writeByte(this.bValid ? (byte) 1 : (byte) 0);
        dest.writeInt(this.assetId);
        dest.writeString(this.voiceName);
    }

    protected VoiceAnalysisInfo(Parcel in) {
        this.startTimeMs = in.readInt();
        this.endTimeMs = in.readInt();
        this.pitchSeq = new ArrayList <VoicePitchInfo>();
        in.readList(this.pitchSeq, VoicePitchInfo.class.getClassLoader());
        this.noteSeq = new ArrayList <VoiceNoteInfo>();
        in.readList(this.noteSeq, VoiceNoteInfo.class.getClassLoader());
        this.bValid = in.readByte() != 0;
        this.assetId = in.readInt();
        this.voiceName = in.readString();
    }

    public static final Creator <VoiceAnalysisInfo> CREATOR = new Creator <VoiceAnalysisInfo>() {
        @Override
        public VoiceAnalysisInfo createFromParcel(Parcel source) {
            return new VoiceAnalysisInfo(source);
        }

        @Override
        public VoiceAnalysisInfo[] newArray(int size) {
            return new VoiceAnalysisInfo[size];
        }
    };
}
