// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

package com.dc.platform.voicebeating;

public final class VoiceAssetInfo {


    /*package*/ final int assetId;

    /*package*/ final String assetName;

    public VoiceAssetInfo(
            int assetId,
            String assetName) {
        this.assetId = assetId;
        this.assetName = assetName;
    }

    public int getAssetId() {
        return assetId;
    }

    public String getAssetName() {
        return assetName;
    }

    @Override
    public String toString() {
        return "VoiceAssetInfo{" +
                "assetId=" + assetId +
                "," + "assetName=" + assetName +
        "}";
    }

}
