// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ffmpeg.djinni

#pragma once

#include <functional>

namespace dc { namespace platform {

enum class FfmpegLogLevel : int {
    LOG_VERBOSE,
    LOG_DEBUG,
    LOG_INFO,
    LOG_WARN,
    LOG_ERROR,
    LOG_FATAL,
    LOG_NONE,
};

} }  // namespace dc::platform

namespace std {

template <>
struct hash<::dc::platform::FfmpegLogLevel> {
    size_t operator()(::dc::platform::FfmpegLogLevel type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
