// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ffmpeg.djinni

#pragma once

#include "ffmpeg_log_level.hpp"

namespace dc { namespace platform {

class FfmpegConfiguration {
public:
    virtual ~FfmpegConfiguration() {}

    static void SetLogLevel(FfmpegLogLevel level);
};

} }  // namespace dc::platform
