// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ffmpeg.djinni

#include "NativeFfmpegWatermark.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeFfmpegWatermark::NativeFfmpegWatermark() = default;

NativeFfmpegWatermark::~NativeFfmpegWatermark() = default;

auto NativeFfmpegWatermark::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeFfmpegWatermark>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.image)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.x)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.y)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.from_time)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.duration)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeFfmpegWatermark::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 6);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeFfmpegWatermark>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_image)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_x)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_y)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_fromTime)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_duration))};
}

}  // namespace djinni_generated
