// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ffmpeg.djinni

package com.dongci.sun.gpuimglibrary.libffmpeg;

public final class FfmpegWatermark {


    /*package*/ final String image;

    /*package*/ final int x;

    /*package*/ final int y;

    /*package*/ final float fromTime;

    /*package*/ final float duration;

    public FfmpegWatermark(
            String image,
            int x,
            int y,
            float fromTime,
            float duration) {
        this.image = image;
        this.x = x;
        this.y = y;
        this.fromTime = fromTime;
        this.duration = duration;
    }

    public String getImage() {
        return image;
    }

    public int getX() {
        return x;
    }

    public int getY() {
        return y;
    }

    public float getFromTime() {
        return fromTime;
    }

    public float getDuration() {
        return duration;
    }
}
