// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ffmpeg.djinni

#pragma once

#include "djinni_support.hpp"
#include "ffmpeg_log_level.hpp"

namespace djinni_generated {

class NativeFfmpegLogLevel final : ::djinni::JniEnum {
public:
    using CppType = ::dc::platform::FfmpegLogLevel;
    using JniType = jobject;

    using Boxed = NativeFfmpegLogLevel;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeFfmpegLogLevel>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeFfmpegLogLevel>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeFfmpegLogLevel() : JniEnum("com/dongci/sun/gpuimglibrary/libffmpeg/FfmpegLogLevel") {}
    friend ::djinni::JniClass<NativeFfmpegLogLevel>;
};

}  // namespace djinni_generated
