// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ffmpeg.djinni

#include "NativeTranscodeListener.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeTranscodeListener::NativeTranscodeListener() : ::djinni::JniInterface<::dc::platform::TranscodeListener, NativeTranscodeListener>() {}

NativeTranscodeListener::~NativeTranscodeListener() = default;

NativeTranscodeListener::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeTranscodeListener::JavaProxy::~JavaProxy() = default;

void NativeTranscodeListener::JavaProxy::OnProcess(float c_percent) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeTranscodeListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onProcess,
                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c_percent)));
    ::djinni::jniExceptionCheck(jniEnv);
}




}  // namespace djinni_generated
