// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ffmpeg.djinni

#pragma once

#include "djinni_support.hpp"
#include "ffmpeg_processor.hpp"

namespace djinni_generated {

class NativeFfmpegProcessor final : ::djinni::JniInterface<::dc::platform::FfmpegProcessor, NativeFfmpegProcessor> {
public:
    using CppType = std::shared_ptr<::dc::platform::FfmpegProcessor>;
    using JniType = jobject;

    using Boxed = NativeFfmpegProcessor;

    ~NativeFfmpegProcessor();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeFfmpegProcessor>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<NativeFfmpegProcessor>::get()._toJava(jniEnv, c)}; }

private:
    NativeFfmpegProcessor();
    friend ::djinni::JniClass<NativeFfmpegProcessor>;
    friend ::djinni::JniInterface<::dc::platform::FfmpegProcessor, NativeFfmpegProcessor>;

};

}  // namespace djinni_generated
