// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ffmpeg.djinni

#include "NativeFfmpegConfiguration.hpp"  // my header
#include "NativeFfmpegLogLevel.hpp"

namespace djinni_generated {

NativeFfmpegConfiguration::NativeFfmpegConfiguration() : ::djinni::JniInterface<::dc::platform::FfmpegConfiguration, NativeFfmpegConfiguration>("com/dongci/sun/gpuimglibrary/libffmpeg/FfmpegConfiguration$CppProxy") {}

NativeFfmpegConfiguration::~NativeFfmpegConfiguration() = default;


CJNIEXPORT void JNICALL Java_com_dongci_sun_gpuimglibrary_libffmpeg_FfmpegConfiguration_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<djinni::CppProxyHandle<::dc::platform::FfmpegConfiguration>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_dongci_sun_gpuimglibrary_libffmpeg_FfmpegConfiguration_setLogLevel(JNIEnv* jniEnv, jobject /*this*/, jobject j_level)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        ::dc::platform::FfmpegConfiguration::SetLogLevel(::djinni_generated::NativeFfmpegLogLevel::toCpp(jniEnv, j_level));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
