// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

package com.dc.platform.voicebeating;

public abstract class NotifyCallback {
    public abstract void dataReadyCallback();
}
