// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

package com.dc.platform.voicebeating;

import java.util.ArrayList;

public final class VoiceTrackInfo {


    /*package*/ final int trackId;

    /*package*/ final ArrayList<VoiceNodeInfo> voiceInfo;

    public VoiceTrackInfo(
            int trackId,
            ArrayList<VoiceNodeInfo> voiceInfo) {
        this.trackId = trackId;
        this.voiceInfo = voiceInfo;
    }

    public int getTrackId() {
        return trackId;
    }

    public ArrayList<VoiceNodeInfo> getVoiceInfo() {
        return voiceInfo;
    }

    @Override
    public String toString() {
        return "VoiceTrackInfo{" +
                "trackId=" + trackId +
                "," + "voiceInfo=" + voiceInfo +
        "}";
    }

}
