// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

package com.dc.platform.voicebeating;

public final class VoiceNodeInfo {


    /*package*/ final int inputStartTime;

    /*package*/ final int inputEndTime;

    /*package*/ final int outputStartTime;

    /*package*/ final float scale;

    /*package*/ final int outputEndTime;

    public VoiceNodeInfo(
            int inputStartTime,
            int inputEndTime,
            int outputStartTime,
            float scale,
            int outputEndTime) {
        this.inputStartTime = inputStartTime;
        this.inputEndTime = inputEndTime;
        this.outputStartTime = outputStartTime;
        this.scale = scale;
        this.outputEndTime = outputEndTime;
    }

    public int getInputStartTime() {
        return inputStartTime;
    }

    public int getInputEndTime() {
        return inputEndTime;
    }

    public int getOutputStartTime() {
        return outputStartTime;
    }

    public float getScale() {
        return scale;
    }

    public int getOutputEndTime() {
        return outputEndTime;
    }

    @Override
    public String toString() {
        return "VoiceNodeInfo{" +
                "inputStartTime=" + inputStartTime +
                "," + "inputEndTime=" + inputEndTime +
                "," + "outputStartTime=" + outputStartTime +
                "," + "scale=" + scale +
                "," + "outputEndTime=" + outputEndTime +
        "}";
    }

}
