// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

package com.dc.platform.voicebeating;

import android.os.Parcel;
import android.os.Parcelable;

public final class VoiceNoteInfo implements Parcelable {


    /*package*/ int startTimeMs;

    /*package*/ int endTimeMs;

    /*package*/ int startFrameIndex;

    /*package*/ int endFrameIndex;

    /*package*/ float note;

    public VoiceNoteInfo(){}

    public VoiceNoteInfo(
            int startTimeMs,
            int endTimeMs,
            int startFrameIndex,
            int endFrameIndex,
            float note) {
        this.startTimeMs = startTimeMs;
        this.endTimeMs = endTimeMs;
        this.startFrameIndex = startFrameIndex;
        this.endFrameIndex = endFrameIndex;
        this.note = note;
    }

    public int getStartTimeMs() {
        return startTimeMs;
    }

    public int getEndTimeMs() {
        return endTimeMs;
    }

    public int getStartFrameIndex() {
        return startFrameIndex;
    }

    public int getEndFrameIndex() {
        return endFrameIndex;
    }

    public float getNote() {
        return note;
    }

    @Override
    public String toString() {
        return "VoiceNoteInfo{" +
                "startTimeMs=" + startTimeMs +
                "," + "endTimeMs=" + endTimeMs +
                "," + "startFrameIndex=" + startFrameIndex +
                "," + "endFrameIndex=" + endFrameIndex +
                "," + "note=" + note +
        "}";
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeInt(this.startTimeMs);
        dest.writeInt(this.endTimeMs);
        dest.writeInt(this.startFrameIndex);
        dest.writeInt(this.endFrameIndex);
        dest.writeFloat(this.note);
    }

    protected VoiceNoteInfo(Parcel in) {
        this.startTimeMs = in.readInt();
        this.endTimeMs = in.readInt();
        this.startFrameIndex = in.readInt();
        this.endFrameIndex = in.readInt();
        this.note = in.readFloat();
    }

    public static final Creator <VoiceNoteInfo> CREATOR = new Creator <VoiceNoteInfo>() {
        @Override
        public VoiceNoteInfo createFromParcel(Parcel source) {
            return new VoiceNoteInfo(source);
        }

        @Override
        public VoiceNoteInfo[] newArray(int size) {
            return new VoiceNoteInfo[size];
        }
    };
}
