// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

package com.dc.platform.voicebeating;

import java.util.ArrayList;

public final class VoiceInputInfo {


    /*package*/ final String midiFileName;

    /*package*/ final String configFileName;

    /*package*/ final ArrayList<VoiceAssetInfo> assetInfos;

    /*package*/ final ArrayList<VoiceAnalysisInfo> analysisInfos;

    /*package*/ final String outFileName;

    public VoiceInputInfo(
            String midiFileName,
            String configFileName,
            ArrayList<VoiceAssetInfo> assetInfos,
            ArrayList<VoiceAnalysisInfo> analysisInfos,
            String outFileName) {
        this.midiFileName = midiFileName;
        this.configFileName = configFileName;
        this.assetInfos = assetInfos;
        this.analysisInfos = analysisInfos;
        this.outFileName = outFileName;
    }

    public String getMidiFileName() {
        return midiFileName;
    }

    public String getConfigFileName() {
        return configFileName;
    }

    public ArrayList<VoiceAssetInfo> getAssetInfos() {
        return assetInfos;
    }

    public ArrayList<VoiceAnalysisInfo> getAnalysisInfos() {
        return analysisInfos;
    }

    public String getOutFileName() {
        return outFileName;
    }

    @Override
    public String toString() {
        return "VoiceInputInfo{" +
                "midiFileName=" + midiFileName +
                "," + "configFileName=" + configFileName +
                "," + "assetInfos=" + assetInfos +
                "," + "analysisInfos=" + analysisInfos +
                "," + "outFileName=" + outFileName +
        "}";
    }

}
