// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from voicebeating.djinni

package com.dc.platform.voicebeating;

import android.os.Parcel;
import android.os.Parcelable;

public final class VoicePitchInfo implements Parcelable {


    /*package*/ int startTimeMs;

    /*package*/ int endTimeMs;

    /*package*/ int startFrameIndex;

    /*package*/ int endFrameIndex;

    /*package*/ float freq;
    public VoicePitchInfo(){}


    public VoicePitchInfo(
            int startTimeMs,
            int endTimeMs,
            int startFrameIndex,
            int endFrameIndex,
            float freq) {
        this.startTimeMs = startTimeMs;
        this.endTimeMs = endTimeMs;
        this.startFrameIndex = startFrameIndex;
        this.endFrameIndex = endFrameIndex;
        this.freq = freq;
    }

    public int getStartTimeMs() {
        return startTimeMs;
    }

    public int getEndTimeMs() {
        return endTimeMs;
    }

    public int getStartFrameIndex() {
        return startFrameIndex;
    }

    public int getEndFrameIndex() {
        return endFrameIndex;
    }

    public float getFreq() {
        return freq;
    }

    @Override
    public String toString() {
        return "VoicePitchInfo{" +
                "startTimeMs=" + startTimeMs +
                "," + "endTimeMs=" + endTimeMs +
                "," + "startFrameIndex=" + startFrameIndex +
                "," + "endFrameIndex=" + endFrameIndex +
                "," + "freq=" + freq +
        "}";
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeInt(this.startTimeMs);
        dest.writeInt(this.endTimeMs);
        dest.writeInt(this.startFrameIndex);
        dest.writeInt(this.endFrameIndex);
        dest.writeFloat(this.freq);
    }

    protected VoicePitchInfo(Parcel in) {
        this.startTimeMs = in.readInt();
        this.endTimeMs = in.readInt();
        this.startFrameIndex = in.readInt();
        this.endFrameIndex = in.readInt();
        this.freq = in.readFloat();
    }

    public static final Creator <VoicePitchInfo> CREATOR = new Creator <VoicePitchInfo>() {
        @Override
        public VoicePitchInfo createFromParcel(Parcel source) {
            return new VoicePitchInfo(source);
        }

        @Override
        public VoicePitchInfo[] newArray(int size) {
            return new VoicePitchInfo[size];
        }
    };
}
